"""create protocol templates table

Revision ID: 0f68a44361b0
Revises: bbd7b9d6868c
Create Date: 2026-08-30 20:33:30.821927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f68a44361b0'
down_revision: Union[str, Sequence[str], None] = 'bbd7b9d6868c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('treatment_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('preparation_parameters', sa.JSON(), nullable=True),
    sa.Column('administration_parameters', sa.JSON(), nullable=True),
    sa.Column('monitoring_parameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_templates_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_protocol_templates_treatment_type'), ['treatment_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocol_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_templates_treatment_type'))
        batch_op.drop_index(batch_op.f('ix_protocol_templates_code'))

    op.drop_table('protocol_templates')
    # ### end Alembic commands ###
