"""add treatment execution snapshot

Revision ID: 47092c136201
Revises: 866febff5eb8
Create Date: 2026-08-31 08:39:00.964030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47092c136201'
down_revision: Union[str, Sequence[str], None] = '866febff5eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocol_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('execution_parameters', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_column('execution_parameters')
        batch_op.drop_column('protocol_snapshot')

    # ### end Alembic commands ###
