"""add treatment components

Revision ID: 6adf71221e0b
Revises: b48fc986ef91
Create Date: 2026-09-01 10:12:30.302785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adf71221e0b'
down_revision: Union[str, Sequence[str], None] = 'b48fc986ef91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('treatment_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('planned_amount IS NULL OR planned_amount > 0', name='ck_treatment_components_positive_amount'),
    sa.CheckConstraint('sequence >= 1', name='ck_treatment_components_positive_sequence'),
    sa.ForeignKeyConstraint(['material_id'], ['orthobiologic_materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('treatment_id', 'material_id', name='uq_treatment_components_treatment_material'),
    sa.UniqueConstraint('treatment_id', 'sequence', name='uq_treatment_components_treatment_sequence')
    )
    with op.batch_alter_table('treatment_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_components_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_components_treatment_id'), ['treatment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_components_treatment_id'))
        batch_op.drop_index(batch_op.f('ix_treatment_components_material_id'))

    op.drop_table('treatment_components')
    # ### end Alembic commands ###
