"""add audit actor attribution

Revision ID: 85f2c25ec4c1
Revises: 6c793aa748f0
Create Date: 2026-08-31 12:00:27.154284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f2c25ec4c1'
down_revision: Union[str, Sequence[str], None] = '6c793aa748f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_user_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('actor_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('actor_display_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('actor_role', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_column('actor_role')
        batch_op.drop_column('actor_display_name')
        batch_op.drop_column('actor_username')
        batch_op.drop_column('actor_user_id')

    # ### end Alembic commands ###
