"""create treatment sessions table

Revision ID: 99e0049e3d44
Revises: 47092c136201
Create Date: 2026-08-31 08:50:50.762245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e0049e3d44'
down_revision: Union[str, Sequence[str], None] = '47092c136201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('treatment_id', sa.String(length=36), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_region', sa.String(length=100), nullable=True),
    sa.Column('dose_or_volume', sa.String(length=100), nullable=True),
    sa.Column('execution_parameters', sa.JSON(), nullable=True),
    sa.Column('outcome_summary', sa.Text(), nullable=True),
    sa.Column('adverse_events', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('treatment_id', 'session_number', name='uq_treatment_sessions_treatment_number')
    )
    with op.batch_alter_table('treatment_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_sessions_treatment_id'), ['treatment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_sessions_treatment_id'))

    op.drop_table('treatment_sessions')
    # ### end Alembic commands ###
