"""add orthobiologic material catalog

Revision ID: b48fc986ef91
Revises: c413a7e28a61
Create Date: 2026-08-31 20:56:59.516311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48fc986ef91'
down_revision: Union[str, Sequence[str], None] = 'c413a7e28a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orthobiologic_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('default_unit', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_autologous', sa.Boolean(), nullable=False),
    sa.Column('requires_lot_tracking', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orthobiologic_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orthobiologic_materials_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_orthobiologic_materials_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_orthobiologic_materials_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orthobiologic_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orthobiologic_materials_is_active'))
        batch_op.drop_index(batch_op.f('ix_orthobiologic_materials_code'))
        batch_op.drop_index(batch_op.f('ix_orthobiologic_materials_category'))

    op.drop_table('orthobiologic_materials')
    # ### end Alembic commands ###
