"""create treatments table

Revision ID: bbd7b9d6868c
Revises: c3e81ad451f3
Create Date: 2026-08-30 19:19:02.971940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd7b9d6868c'
down_revision: Union[str, Sequence[str], None] = 'c3e81ad451f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('treatment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('body_region', sa.String(length=100), nullable=True),
    sa.Column('protocol_name', sa.String(length=200), nullable=True),
    sa.Column('dose_or_volume', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatments_treatment_type'), ['treatment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatments_visit_id'), ['visit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatments_visit_id'))
        batch_op.drop_index(batch_op.f('ix_treatments_treatment_type'))

    op.drop_table('treatments')
    # ### end Alembic commands ###
