"""add treatment session components

Revision ID: c68b24017654
Revises: 6adf71221e0b
Create Date: 2026-09-01 10:58:11.559475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68b24017654'
down_revision: Union[str, Sequence[str], None] = '6adf71221e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_session_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('treatment_session_id', sa.String(length=36), nullable=False),
    sa.Column('treatment_component_id', sa.String(length=36), nullable=True),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('concentration', sa.String(length=100), nullable=True),
    sa.Column('preparation_method', sa.Text(), nullable=True),
    sa.Column('activation_method', sa.Text(), nullable=True),
    sa.Column('storage_condition', sa.String(length=200), nullable=True),
    sa.Column('preparation_parameters', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('actual_amount IS NULL OR actual_amount > 0', name='ck_treatment_session_components_positive_amount'),
    sa.CheckConstraint('sequence >= 1', name='ck_treatment_session_components_positive_sequence'),
    sa.ForeignKeyConstraint(['material_id'], ['orthobiologic_materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['treatment_component_id'], ['treatment_components.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['treatment_session_id'], ['treatment_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('treatment_session_id', 'sequence', name='uq_treatment_session_components_session_sequence')
    )
    with op.batch_alter_table('treatment_session_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_session_components_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_session_components_lot_number'), ['lot_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_session_components_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_session_components_treatment_component_id'), ['treatment_component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_session_components_treatment_session_id'), ['treatment_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment_session_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_session_components_treatment_session_id'))
        batch_op.drop_index(batch_op.f('ix_treatment_session_components_treatment_component_id'))
        batch_op.drop_index(batch_op.f('ix_treatment_session_components_material_id'))
        batch_op.drop_index(batch_op.f('ix_treatment_session_components_lot_number'))
        batch_op.drop_index(batch_op.f('ix_treatment_session_components_batch_number'))

    op.drop_table('treatment_session_components')
    # ### end Alembic commands ###
